version: '2'
services:
        kcp_test_client:
                image: client:latest
                restart: always
                environment:
                        KCP_SERVER_IP: 192.168.1.5
                        KCP_SERVER_PORT: 2443
                        KCP_LOCAL_LISTEN_POR: 8338
                        KCP_LOCAL_MODE: fast2
                        SS_SERVER_PASSWD: 12345678
                        SS_SERVER_ENCRYPT_METHON: aes-256-cfb
                        SS_LOCAL_PORT: 1080
                        KCP_KEY: none
                        KCP_CLIENT_CRYPT: none
                ports:
                        - 8118:8118
                        - 1080:1080
                        - 8338:8338
                        - 8338:8338/udp
