version: '2'
services:
        ss_kcp_server:
                image: server:latest
                restart: always
                environment:
                        SS_SERVER_LISTEN_PORT: 8443
                        SS_SERVER_PASSWD: 12345678
                        SS_SERVER_ENCRYPT_METHON: aes-256-cfb
                        KCP_SERVER_PORT: 9443
                        KCP_SERVER_MODE: fast2
                        KCP_KEY: none
                        KCP_SERVER_CRYPT: none
                ports:
                        - 8443:8443
                        - 8443:8443/udp
                        - 9443:9443/udp
