#!/bin/sh


KCP_SERVER_LISTEN_TARGET_IP=127.0.0.1
KCP_SERVER_LISTEN_TARGET_PORT=${SS_SERVER_LISTEN_PORT}
TARGET_LINK="$KCP_SERVER_LISTEN_TARGET_IP:$KCP_SERVER_LISTEN_TARGET_PORT"
KCP_SERVER_PORT=${KCP_SERVER_PORT}
KCP_KEY=${KCP_KEY}
KCP_SERVER_MODE=${KCP_SERVER_MODE}
KCP_SERVER_CRYPT=${KCP_SERVER_CRYPT}
KCP_MTU=${KCP_MTU}
KCP_SERVER_SNDWND=${KCP_SERVER_SNDWND}

./server_linux_amd64 -t $TARGET_LINK -l ":$KCP_SERVER_PORT" --key $KCP_KEY --crypt $KCP_SERVER_CRYPT -mode $KCP_SERVER_MODE --mtu $KCP_MTU --sndwnd $KCP_SERVER_SNDWND
