#!/bin/sh


KCP_SERVER_IP=${KCP_SERVER_IP}
KCP_SERVER_PORT=${KCP_SERVER_PORT}
SERVER_LINK="$KCP_SERVER_IP:$KCP_SERVER_PORT"
KCP_LOCAL_LISTEN_PORT=${KCP_LOCAL_LISTEN_PORT}
KCP_LOCAL_MODE=${KCP_LOCAL_MODE}
./client_linux_arm7 -r $SERVER_LINK -l ":$KCP_LOCAL_LISTEN_PORT" -mode $KCP_LOCAL_MODE
