#!/bin/sh

SS_SERVER_LISTEN_PORT=${SS_SERVER_LISTEN_PORT}
SS_SERVER_PASSWD=${SS_SERVER_PASSWD}
SS_SERVER_ENCRYPT_METHOD=${SS_SERVER_ENCRYPT_METHOD}
nohup ./ssserver -s [::]:$SS_SERVER_LISTEN_PORT -k $SS_SERVER_PASSWD -m $SS_SERVER_ENCRYPT_METHOD -u >/dev/null 2>&1 &
